runtime: Default copy constructors with user destructors
Fixes -Werror,-Wdeprecated errors such as:
error: definition of implicit copy constructor for 'OatQuickMethodHeader'
is deprecated because it has a user-declared destructor

Change-Id: I8503d01e1cec485a75faa6887b1c068484c93469